### PR TITLE
sdl2.nim needs this fix in line 1377

### PR DESCRIPTION
**Pull request by Jervac**
from
proc dXGIGetOutputInfo* (displayIndex: cint, adapterIndex,outputIndex: ptr cint): void
to
sdl2.dXGIGetOutputInfo(displayIndex: cint, adapterIndex: ptr cint, outputIndex: ptr cint)

### CODE REVIEW

**Comment by Jervac** [comment]
There's also an indentation error on line 1381 after this.

**Comment by def-** [comment]
I don't understand this change, that looks wrong.

**Comment by Jervac** [comment]
Without it, sdl2 can not compile: 
sdl2.nim(1377, 7) Error: implementation of 'sdl2.dXGIGetOutputInfo(displayIndex: cint, adapterIndex: ptr cint, outputIndex: ptr cint)' expected

> Process terminated with exit code 1

**Comment by dom96** [comment]
I don't think this code will compile.

**Comment by Jervac** [comment]
Does the sdl2 work with nim yet? Or am I doing something wrong?

**Comment by def-** [comment]
on Linux at least it works. But this is Windows specific code, so someone with Windows should take a look.

**Comment by Jervac** [comment]
Should this be put under issues then?

**Comment by dom96** [comment]
@def- You can check with ``--os:windows``.

**Comment by fowlmouth** [comment]
those functions need importc pragmas
previously they were named with the same capitalization sdl uses now every function needs importc pragma since function names are lowercase

**Comment by def-** [comment]
Alright, should be fixed for the functions I found in https://github.com/nim-lang/sdl2/commit/c0e931947353f543a9bf7d2818b6bb1999279a1f

**Pull request closed without merging**
