### PR TITLE
Added wrapper for haptic

### PR DESCRIPTION
**Pull request by AllNamesRTaken**
Loads of comments. They bother me but the original had them.

### CODE REVIEW

**Comment by fowlmouth** [comment]
* the `type` fields should be called `kind` 
* functions like `HapticRumbleSupported` should be named `rumbleSupported`, that is functions that include the name of the type that it operates on in the first parameter.
* all functions should start with a lowercase letter

other than that it looks fine, im not worried about the comments, if someone wants to later they can move the comments to under the function name so they'd show up in documentation

**Comment by AllNamesRTaken** [comment]
but the type fields are in structs used by SDL and dont denote an enum or so. Shouldn't they be kept as is for SDL to be happy?

**Comment by AllNamesRTaken** [comment]
I changed the type to kind locally but should I chage `end` to something easier as well?

**Comment by fowlmouth** [comment]
yes please use `last` or `fin` or `finish` or something similar for `end` and merge when you're done

**Pull request merged**
