### PR TITLE
Normalize whitespace.

### PR DESCRIPTION
**Pull request by markus-oberhumer**
Convert files to Unix EOL mode, de-tabify and strip trailing whitespace.

### CODE REVIEW

**Comment by Araq** [comment]
Cannot do a code review on this diff. Sorry. Just live with the whitespace for now. Eventually git might realize it sucks at binary data anyway and should treat source code as text.

**Comment by markus-oberhumer** [comment]
Well, just pull into a local branch and run `git diff -w` to verify that nothing except whitepace has changed.

**Comment by zah** [comment]
It's possible to view the diff without the white-space changes directly in Github:
https://github.com/nim-lang/sdl2/pull/95/files?w=1

In this case, only the white-space is changed indeed.

**Comment by markus-oberhumer** [comment]
@zah Nice, where is this GitHub feature documented? Are there any other useful options?

**Comment by zah** [comment]
https://github.com/tiimgreen/github-cheat-sheet

**Comment by Araq** [comment]
Ah right, forgot about that option, my bad.

**Pull request merged**
