### PR TITLE
SDL_GameController bindings

### PR DESCRIPTION
**Pull request by Woflox**
Adds a new module, gamecontroller.nim, with bindings for the SDL_GameController functions and types. Also fixes compile errors in the joystick module, which this module depends on.

### CODE REVIEW

**Comment by def-** [comment]
Looks good to me.

**Comment by AllNamesRTaken** [comment]
Thanks for stealing

**Comment by Woflox** [comment]
I'm sorry? What do you mean?

**Comment by AllNamesRTaken** [comment]
nm. if it works it works
have you checked that the case of creates a union?

**Comment by Woflox** [comment]
I wasn't aware of the changes on your branch. If you look at the files, they are different and you can see my individual commits (For example, I used object variants in the GameControllerButtonBind object).

Yes I checked that the object variant works, at least for buttons and axis events, I'm not sure where hat bindings come from.

**Comment by AllNamesRTaken** [comment]
I didnt generate mine but those procs to get hat and button as well as that double hatmask doesnt look like the c code or am I just thinking wrong?

**Comment by Woflox** [comment]
The procs to get hat and button were removed with the last commit which added the object variant stuff.

Yes, it creates a union, actually it looks like the pad variables are unnecessary:

```struct  gamecontrollerbuttonbind735033  {
NI32 Bindtype;
union {
struct {int Pad1;
int Pad2;
} S1;
struct {int Button;
int Pad3;
} S2;
struct {int Axis;
int Pad4;
} S3;
struct {int Hat;
int Hatmask;
} S4;
} bindtypeU;
};```

**Comment by AllNamesRTaken** [comment]
All ok then. should I merge?

**Comment by AllNamesRTaken** [comment]
were pads added by c2nim or by you?

**Comment by Woflox** [comment]
I added them, actually I didn't use c2nim

**Comment by AllNamesRTaken** [comment]
then just remove them and i merge

**Comment by Woflox** [comment]
Thanks! Sorry if I stepped on your toes a bit, this was actually my first contribution to an open source project (believe it or not).

**Comment by superfunc** [comment]
Welcome to Nim @Woflox

**Comment by AllNamesRTaken** [comment]
are you doing haptic as well or should I give it a go?

**Comment by Woflox** [comment]
Go ahead, I'm back to my own stuff for now.

**Comment by AllNamesRTaken** [comment]
Thanks for your contrib any way

**Pull request merged**
