### PR TITLE
Made gamecontroller more consistent.

### PR DESCRIPTION
**Pull request by G4MR**
There's really no reason to mix the function name conventions.  We need to make each file as consistent as possible.

### CODE REVIEW

**Comment by fowlmouth** [comment]
This is not consistent, notice we have `copy()` instead of `renderer_copy()`

**Comment by fowlmouth** [comment]
Since these functions operate on a game controller having game controller in their name is redundant

**Comment by G4MR** [comment]
I think you misunderstand what I mean by consistent.  Half that file is different than the other half.

**Comment by G4MR** [comment]
tbh half of the SDL2 port is inconsistent and I'm talking file to file.  If we want the library to be consistent across files, we need to start with each file first individually and making sure their naming conventions are the same first.  

We have functions called `gameControllerAddMapping` (which is the original function name) versus half the functions that read `close`, `getButton`.  This is just this file alone, keycodes.nim file you have the original `SDL_SCANCODE_X` while someone changed the keycode's to a minimalized version of just `K_X` you see what I'm getting at.  Each file on its own isn't consistent to begin with.

**Comment by fowlmouth** [comment]
functions that operate on a type have shortened names so you don't have to type out `typename_close(obj)`
I'd rather the module prefixes like `gameController` be removed completely and require `gameController.fn()` if fn clashes. then again, originally all functions from SDL2.dll were in one module and required this prefix

**Comment by G4MR** [comment]
Yeah I get that, point being though before I made this PR, half of that file doesn't use the module prefix eg.: `gameController.gameControllerAddMapping` and it also contains `gameController.close` this isn't the only file with inconsistencies.  I'd rather make all the functions the same then go through and change them to the module prefix thing that you want.  Personally I kind of just want the fork the whole thing and redo a lot of it.

**Comment by fowlmouth** [comment]
Eh alright I'm fine with removing the module prefixes, I noticed sdl2/joystick is sloppily done too. Your work here is appreciated!

**Comment by AllNamesRTaken** [comment]
I am sure G4MR has all under control but the convention to type myObject.open instead of someTypeOpen(MyObject) add or remove module prefix on that is what I though was the norm. This PR is doing the opposite. What is so inconsistant in Joystick or Gamepad? Those taking a Joystick type doesnt have Joystick in their names and those taking a cstring or so does.

If we should just jump ship and type it all out like it sais in the SDL API. Im ok with that too since that would make looking funktions up easier, but I was under the impression that this wasnt just a port 1 to 1 like https://github.com/Vladar4/sdl2-nim. But then I am also very tired.

**Comment by G4MR** [comment]
@AllNamesRTaken Just to save you some time look at the current source https://github.com/nim-lang/sdl2/blob/master/src/sdl2/gamecontroller.nim 

I'm personally too unmotivated to do anything right now though so I'm closing this.

**Comment by fowlmouth** [comment]
I will fix it by moving the rogue modules joystick, gamecontroller and haptic into sdl2.nim where they should have been from the start

**Pull request closed without merging**
