### PR TITLE
Add getQueuedAudioSize() and queueAudio()

### PR DESCRIPTION
**Pull request by trustable-code**

### CODE REVIEW

**Comment by trustable-code** [comment]
Hm, looks partly redundant to https://github.com/nim-lang/sdl2/pull/92

**Comment by dom96** [comment]
Maybe you could do what @Araq suggested, that way I can merge this in and close the other PR :)

**Comment by trustable-code** [comment]
@dom96 In my first commit I had the proc description below instead of above. This is now corrected. I tried to use the correct comment syntax. 
BTW, is there a generated HTML documentation online for this module?

**Comment by dom96** [comment]
Above isn't the correct way to do it...

**Comment by trustable-code** [comment]
@dom96 Do you mean the code or the merge action? Please tell me how to do it better.

**Comment by dom96** [comment]
I mean where you placed the proc description. See how the procs are documented in the stdlib please.

**Pull request merged**
