### PR TITLE
Added SDL2_Mixer support

### PR DESCRIPTION
**Pull request by G4MR**
I've included an example as well, I've only tested on windows 7 so if anyone's willing to test this on linux/mac that would be great.

Binaries can be found here: https://www.libsdl.org/projects/SDL_mixer/

### CODE REVIEW

**Comment by def-** [comment]
Only works with dynamic linking. I recently made all the SDL2 modules work with static linking as well, would be nice if you could add that.

**Comment by G4MR** [comment]
I'll see what I can do (never done that before), will use your code as a reference.

**Comment by def-** [comment]
Looks fine to me now.

**Comment by fowlmouth** [comment]
To fit with the other modules the Mix_ prefix should be removed from functions and their names start lowercased

**Comment by G4MR** [comment]
Alright, working on it.

**Pull request merged**
